package GUI;

import DATA.Project;
import DATA.User;
import DATA.UserCreds;
import MANAGER.ProjectManager;
import MANAGER.UserManager;
import MANAGER.Validator;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class MainForm extends javax.swing.JFrame {

	CardLayout cardLayoutMain;
	CardLayout cardLayoutPV;

	public User currentUser;
	public String currentUsername;

	public MainForm() {
		initComponents();

		this.setLocationRelativeTo(null); // Set to Center
		cardLayoutMain = (CardLayout) (MainPanel.getLayout()); // Get Main card layout
		cardLayoutPV = (CardLayout) (CardPV.getLayout());  // Get PV card layout
	}

	private void refreshProjectView() {  //Loads Project Components for Project View
		ScrollViewPV.removeAll();
		ProjectManager projectManager = new ProjectManager();
		List<Project> projects = projectManager.GetUserProjects(currentUser);
		Dimension preferredSize = new Dimension(818, 174 * projects.size() + 10);
		ScrollViewPV.setPreferredSize(preferredSize);
		ProjectScrollViewPV.getVerticalScrollBar().setUnitIncrement(16);
		ProjectScrollViewPV.getVerticalScrollBar().setAutoscrolls(false);

		for (int i = 0; i < projects.size(); i++) {
			Project project = projects.get(i);
			ProjectTile projectTile = new ProjectTile(project);

			projectTile.setSize(395, 202);
			projectTile.setLocation(140, 206 * i + 5);
			projectTile.setVisible(true);

			ScrollViewPV.add(projectTile);
		}
	}

	private void setAccountDetails() {  // Sets the current users details
		AccountName.setText(currentUser.getUserFirstName() + " " + currentUser.getUserSurname());
		AccountUsername.setText(currentUsername);
	}

	private int calcPassScore(String password) { // Calculates the password strength
		int score = 0;

		//Calc Score
		Pattern upperRegex = Pattern.compile("[A-Z]");
		Pattern lowerRegex = Pattern.compile("[a-z]");
		Pattern numberRegex = Pattern.compile("[0-9]");
		Pattern specialRegex = Pattern.compile(".[!,@,#,$,%,^,&,*,?,_,~,-,£,(,)]");
		int minLength = 8;

		Matcher matcher1 = upperRegex.matcher(password);
		if (matcher1.find()) {
			score++;
		}

		Matcher matcher2 = lowerRegex.matcher(password);
		if (matcher2.find()) {
			score++;
		}

		Matcher matcher3 = numberRegex.matcher(password);
		if (matcher3.find()) {
			score++;
		}

		Matcher matcher4 = specialRegex.matcher(password);
		if (matcher4.find()) {
			score++;
		}

		if (score < 3) {
			score--;
		}

		if (password.length() > minLength) {
			score += Math.floor((password.length() - minLength) / 2);
		}

		if (password.length() < minLength) {
			score = 0;
		}

		return score;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    MainPanel = new javax.swing.JPanel();
    InitialPanel = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    InitTitlePNL = new javax.swing.JPanel();
    Welcome1Text = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    SignUpButton = new javax.swing.JButton();
    SignInButtonPNL = new javax.swing.JButton();
    RegisterPanel = new javax.swing.JPanel();
    RegPNL = new javax.swing.JPanel();
    UsernameText1 = new javax.swing.JLabel();
    UsernameFieldRegPNL = new javax.swing.JTextField();
    UsernameText3 = new javax.swing.JLabel();
    EmailField = new javax.swing.JTextField();
    UsernameText4 = new javax.swing.JLabel();
    UsernameText5 = new javax.swing.JLabel();
    SurnameField = new javax.swing.JTextField();
    FirstNameField = new javax.swing.JTextField();
    UsernameText6 = new javax.swing.JLabel();
    UsernameText7 = new javax.swing.JLabel();
    PasswordFieldRegPNL = new javax.swing.JPasswordField();
    SignUpButtonRegPNL = new javax.swing.JButton();
    ErrorTextRegPNL = new javax.swing.JLabel();
    LoginInsteadButtonRegPNL = new javax.swing.JButton();
    UsernameText8 = new javax.swing.JLabel();
    RepeatedPasswordField = new javax.swing.JPasswordField();
    PasswordStrength = new javax.swing.JProgressBar();
    PassStrengthText = new javax.swing.JLabel();
    DOBPicker = new org.jdesktop.swingx.JXDatePicker();
    LoginPanel = new javax.swing.JPanel();
    LogPNL = new javax.swing.JPanel();
    SignInButtonLogPNL = new javax.swing.JButton();
    UsernameText = new javax.swing.JLabel();
    UsernameField = new javax.swing.JTextField();
    UsernameText2 = new javax.swing.JLabel();
    PasswordField = new javax.swing.JPasswordField();
    ErrorText = new javax.swing.JLabel();
    SignUpInsteadButtonLogPNL = new javax.swing.JButton();
    ProjectView = new javax.swing.JPanel();
    MainSplit = new javax.swing.JSplitPane();
    SidePane = new javax.swing.JPanel();
    AccountPanel = new javax.swing.JPanel();
    AccountName = new javax.swing.JLabel();
    AccountUsername = new javax.swing.JLabel();
    AccountSetButtons = new javax.swing.JButton();
    AccountIcon = new javax.swing.JLabel();
    CardPV = new javax.swing.JPanel();
    ProjectViewCardPV = new javax.swing.JPanel();
    ProjectViewToolBarPV = new javax.swing.JPanel();
    NewProjectButtonPV = new javax.swing.JButton();
    RefreshButtonPV = new javax.swing.JButton();
    ProjectScrollViewPV = new javax.swing.JScrollPane();
    ScrollViewPV = new javax.swing.JPanel();
    NewProjectViewPV = new javax.swing.JPanel();
    NewProjectDetailsPV = new javax.swing.JPanel();
    ProjectNameLabelNPPV = new javax.swing.JLabel();
    ProjectNameTXTNPPV = new javax.swing.JTextField();
    ProjectDescriptionLabelNPPV = new javax.swing.JLabel();
    TextScrollNPPV = new javax.swing.JScrollPane();
    DesriptionTextAreaNPPV = new javax.swing.JTextArea();
    CreateProjectBTNNPPV = new javax.swing.JButton();
    ErrorLabelNPPV = new javax.swing.JLabel();
    ToolBarNPPV = new javax.swing.JPanel();
    BackButton = new javax.swing.JButton();
    SeperatorNPPV = new javax.swing.JSeparator();
    ProjectPage = new javax.swing.JPanel();
    AccountSettingsPanel = new javax.swing.JPanel();
    AccountSettingToolbar = new javax.swing.JPanel();
    AccounSettingsBackButton = new javax.swing.JToggleButton();
    jLabel2 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jPanel2 = new javax.swing.JPanel();
    DeleteAccountButton = new javax.swing.JButton();
    MenuBar = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Just Do It");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setResizable(false);

    MainPanel.setLayout(new java.awt.CardLayout());

    Welcome1Text.setFont(new java.awt.Font("Fredoka One", 1, 36)); // NOI18N
    Welcome1Text.setText("Just Do It");

    jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
    jLabel1.setText("Project Manager");

    javax.swing.GroupLayout InitTitlePNLLayout = new javax.swing.GroupLayout(InitTitlePNL);
    InitTitlePNL.setLayout(InitTitlePNLLayout);
    InitTitlePNLLayout.setHorizontalGroup(
      InitTitlePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InitTitlePNLLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Welcome1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InitTitlePNLLayout.createSequentialGroup()
        .addContainerGap(65, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addGap(47, 47, 47))
    );
    InitTitlePNLLayout.setVerticalGroup(
      InitTitlePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InitTitlePNLLayout.createSequentialGroup()
        .addComponent(Welcome1Text)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addContainerGap())
    );

    SignUpButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
    SignUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-add-user-male-24.png"))); // NOI18N
    SignUpButton.setText("Sign up");
    SignUpButton.setToolTipText("Click To Sign up");
    SignUpButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SignUpButtonActionPerformed(evt);
      }
    });

    SignInButtonPNL.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
    SignInButtonPNL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-login-rounded-26.png"))); // NOI18N
    SignInButtonPNL.setText("Sign in");
    SignInButtonPNL.setToolTipText("Click To Sign in");
    SignInButtonPNL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SignInButtonPNLActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(52, 52, 52)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(SignUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
          .addComponent(SignInButtonPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(73, 73, 73))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(SignInButtonPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 16, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(83, 83, 83)
            .addComponent(InitTitlePNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(72, 72, 72)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(31, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(InitTitlePNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(70, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout InitialPanelLayout = new javax.swing.GroupLayout(InitialPanel);
    InitialPanel.setLayout(InitialPanelLayout);
    InitialPanelLayout.setHorizontalGroup(
      InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InitialPanelLayout.createSequentialGroup()
        .addGap(191, 191, 191)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(220, Short.MAX_VALUE))
    );
    InitialPanelLayout.setVerticalGroup(
      InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InitialPanelLayout.createSequentialGroup()
        .addGap(130, 130, 130)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(152, Short.MAX_VALUE))
    );

    MainPanel.add(InitialPanel, "InitialPanel");

    RegPNL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign Up", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N
    RegPNL.setNextFocusableComponent(UsernameFieldRegPNL);

    UsernameText1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText1.setLabelFor(UsernameField);
    UsernameText1.setText("Username");

    UsernameFieldRegPNL.setToolTipText("Enter Username");
    UsernameFieldRegPNL.setNextFocusableComponent(EmailField);

    UsernameText3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText3.setLabelFor(EmailField);
    UsernameText3.setText("Email");

    EmailField.setToolTipText("Enter Email");

    UsernameText4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText4.setLabelFor(PasswordFieldRegPNL);
    UsernameText4.setText("Password");

    UsernameText5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText5.setLabelFor(SurnameField);
    UsernameText5.setText("Surname");

    SurnameField.setToolTipText("Enter Surname");
    SurnameField.setNextFocusableComponent(UsernameFieldRegPNL);

    FirstNameField.setToolTipText("Enter First Name");
    FirstNameField.setNextFocusableComponent(SurnameField);

    UsernameText6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText6.setLabelFor(FirstNameField);
    UsernameText6.setText("First Name");

    UsernameText7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText7.setText("Date Of Birth");

    PasswordFieldRegPNL.setToolTipText("Enter Password");
    PasswordFieldRegPNL.setNextFocusableComponent(RepeatedPasswordField);
    PasswordFieldRegPNL.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PasswordFieldRegPNLMouseClicked(evt);
      }
    });
    PasswordFieldRegPNL.addInputMethodListener(new java.awt.event.InputMethodListener() {
      public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
      }
      public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
        PasswordFieldRegPNLInputMethodTextChanged(evt);
      }
    });
    PasswordFieldRegPNL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        PasswordFieldRegPNLActionPerformed(evt);
      }
    });
    PasswordFieldRegPNL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        PasswordFieldRegPNLPropertyChange(evt);
      }
    });
    PasswordFieldRegPNL.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        PasswordFieldRegPNLKeyPressed(evt);
      }
      public void keyTyped(java.awt.event.KeyEvent evt) {
        PasswordFieldRegPNLKeyTyped(evt);
      }
    });

    SignUpButtonRegPNL.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
    SignUpButtonRegPNL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-add-user-male-24.png"))); // NOI18N
    SignUpButtonRegPNL.setText("Sign up");
    SignUpButtonRegPNL.setToolTipText("Click To Sign up");
    SignUpButtonRegPNL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SignUpButtonRegPNLActionPerformed(evt);
      }
    });

    ErrorTextRegPNL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    ErrorTextRegPNL.setForeground(new java.awt.Color(255, 0, 51));
    ErrorTextRegPNL.setAutoscrolls(true);
    ErrorTextRegPNL.setFocusable(false);

    LoginInsteadButtonRegPNL.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
    LoginInsteadButtonRegPNL.setText("Login Instead");
    LoginInsteadButtonRegPNL.setToolTipText("Click to switch to Login");
    LoginInsteadButtonRegPNL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        LoginInsteadButtonRegPNLActionPerformed(evt);
      }
    });

    UsernameText8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText8.setLabelFor(RepeatedPasswordField);
    UsernameText8.setText("Confirm Password");

    RepeatedPasswordField.setToolTipText("Renter Password");
    RepeatedPasswordField.setNextFocusableComponent(SignUpButtonRegPNL);
    RepeatedPasswordField.setOpaque(false);

    PassStrengthText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
    PassStrengthText.setLabelFor(PasswordStrength);
    PassStrengthText.setText("Password Strength");

    DOBPicker.setToolTipText("Enter Date of Birth");

    javax.swing.GroupLayout RegPNLLayout = new javax.swing.GroupLayout(RegPNL);
    RegPNL.setLayout(RegPNLLayout);
    RegPNLLayout.setHorizontalGroup(
      RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(RegPNLLayout.createSequentialGroup()
        .addGroup(RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(RegPNLLayout.createSequentialGroup()
            .addGap(147, 147, 147)
            .addComponent(LoginInsteadButtonRegPNL)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(SignUpButtonRegPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(RegPNLLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(ErrorTextRegPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(RegPNLLayout.createSequentialGroup()
                .addGroup(RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(UsernameText3)
                  .addComponent(UsernameText1)
                  .addComponent(UsernameText5)
                  .addComponent(UsernameText6)
                  .addComponent(UsernameFieldRegPNL)
                  .addComponent(SurnameField)
                  .addComponent(FirstNameField)
                  .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(UsernameText8)
                  .addComponent(UsernameText4)
                  .addComponent(UsernameText7)
                  .addComponent(PasswordFieldRegPNL)
                  .addComponent(RepeatedPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                  .addComponent(PasswordStrength, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                  .addComponent(PassStrengthText)
                  .addComponent(DOBPicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        .addContainerGap(45, Short.MAX_VALUE))
    );
    RegPNLLayout.setVerticalGroup(
      RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(RegPNLLayout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(RegPNLLayout.createSequentialGroup()
            .addComponent(UsernameText6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(UsernameText5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(UsernameText1))
          .addGroup(RegPNLLayout.createSequentialGroup()
            .addComponent(UsernameText7)
            .addGap(9, 9, 9)
            .addComponent(DOBPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(UsernameText4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(PasswordFieldRegPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(PassStrengthText)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(RegPNLLayout.createSequentialGroup()
            .addComponent(UsernameFieldRegPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(UsernameText3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(RegPNLLayout.createSequentialGroup()
            .addComponent(PasswordStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UsernameText8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(RepeatedPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addComponent(ErrorTextRegPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(RegPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(LoginInsteadButtonRegPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(SignUpButtonRegPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(32, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
    RegisterPanel.setLayout(RegisterPanelLayout);
    RegisterPanelLayout.setHorizontalGroup(
      RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
        .addContainerGap(135, Short.MAX_VALUE)
        .addComponent(RegPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(121, 121, 121))
    );
    RegisterPanelLayout.setVerticalGroup(
      RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(RegisterPanelLayout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addComponent(RegPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(83, Short.MAX_VALUE))
    );

    MainPanel.add(RegisterPanel, "RegisterPanel");

    LogPNL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N

    SignInButtonLogPNL.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
    SignInButtonLogPNL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-login-rounded-26.png"))); // NOI18N
    SignInButtonLogPNL.setText("Sign in");
    SignInButtonLogPNL.setToolTipText("Click To Sign in");
    SignInButtonLogPNL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SignInButtonLogPNLActionPerformed(evt);
      }
    });

    UsernameText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText.setText("Username");

    UsernameField.setToolTipText("Enter your Username");

    UsernameText2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    UsernameText2.setText("Password");

    PasswordField.setToolTipText("Enter Password");

    ErrorText.setForeground(new java.awt.Color(255, 0, 51));

    SignUpInsteadButtonLogPNL.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
    SignUpInsteadButtonLogPNL.setText("Sign Up Instead");
    SignUpInsteadButtonLogPNL.setToolTipText("Click to Sign Up");
    SignUpInsteadButtonLogPNL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SignUpInsteadButtonLogPNLActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout LogPNLLayout = new javax.swing.GroupLayout(LogPNL);
    LogPNL.setLayout(LogPNLLayout);
    LogPNLLayout.setHorizontalGroup(
      LogPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LogPNLLayout.createSequentialGroup()
        .addGap(86, 86, 86)
        .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogPNLLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(LogPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(PasswordField)
          .addComponent(UsernameField)
          .addGroup(LogPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(LogPNLLayout.createSequentialGroup()
              .addComponent(SignUpInsteadButtonLogPNL)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(SignInButtonLogPNL))
            .addComponent(UsernameText2, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsernameText, javax.swing.GroupLayout.Alignment.LEADING)))
        .addGap(39, 39, 39))
    );
    LogPNLLayout.setVerticalGroup(
      LogPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LogPNLLayout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(UsernameText)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(UsernameText2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(LogPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(SignInButtonLogPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(SignUpInsteadButtonLogPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(266, 266, 266)
        .addComponent(ErrorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
    LoginPanel.setLayout(LoginPanelLayout);
    LoginPanelLayout.setHorizontalGroup(
      LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
        .addContainerGap(243, Short.MAX_VALUE)
        .addComponent(LogPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(230, 230, 230))
    );
    LoginPanelLayout.setVerticalGroup(
      LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LoginPanelLayout.createSequentialGroup()
        .addGap(122, 122, 122)
        .addComponent(LogPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(181, Short.MAX_VALUE))
    );

    MainPanel.add(LoginPanel, "LoginPanel");

    MainSplit.setDividerSize(2);

    SidePane.setEnabled(false);
    SidePane.setPreferredSize(new java.awt.Dimension(200, 0));

    AccountName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
    AccountName.setText("John Doe");
    AccountName.setMaximumSize(new java.awt.Dimension(73, 15));
    AccountName.setMinimumSize(new java.awt.Dimension(73, 15));
    AccountName.setPreferredSize(new java.awt.Dimension(73, 15));

    AccountUsername.setText("johndoe");

    AccountSetButtons.setText("Account Settings");
    AccountSetButtons.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AccountSetButtonsActionPerformed(evt);
      }
    });

    AccountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-account-48.png"))); // NOI18N

    javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
    AccountPanel.setLayout(AccountPanelLayout);
    AccountPanelLayout.setHorizontalGroup(
      AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AccountPanelLayout.createSequentialGroup()
        .addComponent(AccountIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(AccountName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(AccountUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
      .addGroup(AccountPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(AccountSetButtons)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    AccountPanelLayout.setVerticalGroup(
      AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AccountPanelLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(AccountPanelLayout.createSequentialGroup()
            .addComponent(AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(AccountUsername))
          .addComponent(AccountIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(AccountSetButtons)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout SidePaneLayout = new javax.swing.GroupLayout(SidePane);
    SidePane.setLayout(SidePaneLayout);
    SidePaneLayout.setHorizontalGroup(
      SidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(AccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    SidePaneLayout.setVerticalGroup(
      SidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePaneLayout.createSequentialGroup()
        .addGap(0, 484, Short.MAX_VALUE)
        .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    MainSplit.setLeftComponent(SidePane);

    CardPV.setPreferredSize(new java.awt.Dimension(670, 578));
    CardPV.setLayout(new java.awt.CardLayout());

    ProjectViewCardPV.setPreferredSize(new java.awt.Dimension(620, 578));
    ProjectViewCardPV.addContainerListener(new java.awt.event.ContainerAdapter() {
      public void componentAdded(java.awt.event.ContainerEvent evt) {
        ProjectViewCardPVComponentAdded(evt);
      }
    });
    ProjectViewCardPV.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        ProjectViewCardPVComponentShown(evt);
      }
    });

    NewProjectButtonPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-plus-20.png"))); // NOI18N
    NewProjectButtonPV.setText("New Project");
    NewProjectButtonPV.setToolTipText("Click to create new project");
    NewProjectButtonPV.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        NewProjectButtonPVActionPerformed(evt);
      }
    });

    RefreshButtonPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-process-20 (1).png"))); // NOI18N
    RefreshButtonPV.setText("Refresh");
    RefreshButtonPV.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RefreshButtonPVActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ProjectViewToolBarPVLayout = new javax.swing.GroupLayout(ProjectViewToolBarPV);
    ProjectViewToolBarPV.setLayout(ProjectViewToolBarPVLayout);
    ProjectViewToolBarPVLayout.setHorizontalGroup(
      ProjectViewToolBarPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ProjectViewToolBarPVLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(NewProjectButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(RefreshButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    ProjectViewToolBarPVLayout.setVerticalGroup(
      ProjectViewToolBarPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ProjectViewToolBarPVLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ProjectViewToolBarPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(NewProjectButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(RefreshButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    ProjectScrollViewPV.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    ProjectScrollViewPV.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

    javax.swing.GroupLayout ScrollViewPVLayout = new javax.swing.GroupLayout(ScrollViewPV);
    ScrollViewPV.setLayout(ScrollViewPVLayout);
    ScrollViewPVLayout.setHorizontalGroup(
      ScrollViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 818, Short.MAX_VALUE)
    );
    ScrollViewPVLayout.setVerticalGroup(
      ScrollViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 523, Short.MAX_VALUE)
    );

    ProjectScrollViewPV.setViewportView(ScrollViewPV);

    javax.swing.GroupLayout ProjectViewCardPVLayout = new javax.swing.GroupLayout(ProjectViewCardPV);
    ProjectViewCardPV.setLayout(ProjectViewCardPVLayout);
    ProjectViewCardPVLayout.setHorizontalGroup(
      ProjectViewCardPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ProjectViewCardPVLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ProjectViewCardPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(ProjectScrollViewPV, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
          .addGroup(ProjectViewCardPVLayout.createSequentialGroup()
            .addComponent(ProjectViewToolBarPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())))
    );
    ProjectViewCardPVLayout.setVerticalGroup(
      ProjectViewCardPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ProjectViewCardPVLayout.createSequentialGroup()
        .addComponent(ProjectViewToolBarPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ProjectScrollViewPV, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
    );

    CardPV.add(ProjectViewCardPV, "ProjectViewPV");

    NewProjectDetailsPV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create New Project", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 16))); // NOI18N

    ProjectNameLabelNPPV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    ProjectNameLabelNPPV.setText("Project Title");

    ProjectDescriptionLabelNPPV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    ProjectDescriptionLabelNPPV.setText("Project Description");

    DesriptionTextAreaNPPV.setColumns(20);
    DesriptionTextAreaNPPV.setLineWrap(true);
    DesriptionTextAreaNPPV.setRows(5);
    TextScrollNPPV.setViewportView(DesriptionTextAreaNPPV);

    CreateProjectBTNNPPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-plus-20.png"))); // NOI18N
    CreateProjectBTNNPPV.setText("Create");
    CreateProjectBTNNPPV.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        CreateProjectBTNNPPVActionPerformed(evt);
      }
    });

    ErrorLabelNPPV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    ErrorLabelNPPV.setForeground(new java.awt.Color(204, 0, 0));

    javax.swing.GroupLayout NewProjectDetailsPVLayout = new javax.swing.GroupLayout(NewProjectDetailsPV);
    NewProjectDetailsPV.setLayout(NewProjectDetailsPVLayout);
    NewProjectDetailsPVLayout.setHorizontalGroup(
      NewProjectDetailsPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewProjectDetailsPVLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(CreateProjectBTNNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22))
      .addGroup(NewProjectDetailsPVLayout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addGroup(NewProjectDetailsPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(ProjectDescriptionLabelNPPV)
          .addComponent(ProjectNameLabelNPPV)
          .addGroup(NewProjectDetailsPVLayout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(ErrorLabelNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(ProjectNameTXTNPPV)
          .addComponent(TextScrollNPPV))
        .addContainerGap(49, Short.MAX_VALUE))
    );
    NewProjectDetailsPVLayout.setVerticalGroup(
      NewProjectDetailsPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(NewProjectDetailsPVLayout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addComponent(ProjectNameLabelNPPV)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ProjectNameTXTNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(ProjectDescriptionLabelNPPV)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(TextScrollNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ErrorLabelNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        .addComponent(CreateProjectBTNNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22))
    );

    BackButton.setText("Back");
    BackButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BackButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ToolBarNPPVLayout = new javax.swing.GroupLayout(ToolBarNPPV);
    ToolBarNPPV.setLayout(ToolBarNPPVLayout);
    ToolBarNPPVLayout.setHorizontalGroup(
      ToolBarNPPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ToolBarNPPVLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(BackButton)
        .addContainerGap(577, Short.MAX_VALUE))
      .addGroup(ToolBarNPPVLayout.createSequentialGroup()
        .addComponent(SeperatorNPPV)
        .addContainerGap())
    );
    ToolBarNPPVLayout.setVerticalGroup(
      ToolBarNPPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ToolBarNPPVLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(SeperatorNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout NewProjectViewPVLayout = new javax.swing.GroupLayout(NewProjectViewPV);
    NewProjectViewPV.setLayout(NewProjectViewPVLayout);
    NewProjectViewPVLayout.setHorizontalGroup(
      NewProjectViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ToolBarNPPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(NewProjectViewPVLayout.createSequentialGroup()
        .addGap(121, 121, 121)
        .addComponent(NewProjectDetailsPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    NewProjectViewPVLayout.setVerticalGroup(
      NewProjectViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewProjectViewPVLayout.createSequentialGroup()
        .addComponent(ToolBarNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(50, 50, 50)
        .addComponent(NewProjectDetailsPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(93, Short.MAX_VALUE))
    );

    CardPV.add(NewProjectViewPV, "NewProject");

    javax.swing.GroupLayout ProjectPageLayout = new javax.swing.GroupLayout(ProjectPage);
    ProjectPage.setLayout(ProjectPageLayout);
    ProjectPageLayout.setHorizontalGroup(
      ProjectPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 669, Short.MAX_VALUE)
    );
    ProjectPageLayout.setVerticalGroup(
      ProjectPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 578, Short.MAX_VALUE)
    );

    CardPV.add(ProjectPage, "card6");

    AccounSettingsBackButton.setText("Back");
    AccounSettingsBackButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AccounSettingsBackButtonActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
    jLabel2.setText("Account Settings");

    javax.swing.GroupLayout AccountSettingToolbarLayout = new javax.swing.GroupLayout(AccountSettingToolbar);
    AccountSettingToolbar.setLayout(AccountSettingToolbarLayout);
    AccountSettingToolbarLayout.setHorizontalGroup(
      AccountSettingToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AccountSettingToolbarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(AccounSettingsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(164, 164, 164)
        .addComponent(jLabel2)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    AccountSettingToolbarLayout.setVerticalGroup(
      AccountSettingToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountSettingToolbarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(AccountSettingToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(AccounSettingsBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(3, 3, 3)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    DeleteAccountButton.setText("Delete Account");
    DeleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DeleteAccountButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(268, 268, 268)
        .addComponent(DeleteAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(249, 249, 249))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addGap(420, 420, 420)
        .addComponent(DeleteAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        .addGap(64, 64, 64))
    );

    javax.swing.GroupLayout AccountSettingsPanelLayout = new javax.swing.GroupLayout(AccountSettingsPanel);
    AccountSettingsPanel.setLayout(AccountSettingsPanelLayout);
    AccountSettingsPanelLayout.setHorizontalGroup(
      AccountSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AccountSettingsPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(AccountSettingToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    AccountSettingsPanelLayout.setVerticalGroup(
      AccountSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AccountSettingsPanelLayout.createSequentialGroup()
        .addComponent(AccountSettingToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    CardPV.add(AccountSettingsPanel, "AccountSettings");

    MainSplit.setRightComponent(CardPV);

    javax.swing.GroupLayout ProjectViewLayout = new javax.swing.GroupLayout(ProjectView);
    ProjectView.setLayout(ProjectViewLayout);
    ProjectViewLayout.setHorizontalGroup(
      ProjectViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(MainSplit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
    );
    ProjectViewLayout.setVerticalGroup(
      ProjectViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(MainSplit, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    MainPanel.add(ProjectView, "ProjectView");

    jMenu1.setText("File");
    MenuBar.add(jMenu1);

    jMenu2.setText("Edit");
    MenuBar.add(jMenu2);

    setJMenuBar(MenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
		cardLayoutMain.show(MainPanel, "RegisterPanel");  // Switch to Register View
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void SignInButtonPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonPNLActionPerformed
		cardLayoutMain.show(MainPanel, "LoginPanel");  // Switch to Login View
    }//GEN-LAST:event_SignInButtonPNLActionPerformed

        private void SignInButtonLogPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonLogPNLActionPerformed
		// Sign In Logic

		UserManager userManager = new UserManager();
		if (userManager.LoginUser(UsernameField.getText(), new String(PasswordField.getPassword()))) {
			currentUsername = UsernameField.getText();
			currentUser = userManager.getUser(currentUsername);
			cardLayoutMain.show(MainPanel, "ProjectView");
			refreshProjectView();
			setAccountDetails();
			JOptionPane.showMessageDialog(this,
							"✔ Successful Login"
							+ "\nWelcome " + currentUser.getUserFirstName()
			);
		} else {
			JOptionPane.showMessageDialog(this,
							"❌ Username or Password is Incorrect"
							+ "\nPlease Try Again"
			);
		}
        }//GEN-LAST:event_SignInButtonLogPNLActionPerformed

        private void SignUpInsteadButtonLogPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInsteadButtonLogPNLActionPerformed
		cardLayoutMain.show(MainPanel, "RegisterPanel"); //Switch to Register Panel
        }//GEN-LAST:event_SignUpInsteadButtonLogPNLActionPerformed

        private void SignUpButtonRegPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonRegPNLActionPerformed
		// Sign In Logic

		ErrorTextRegPNL.setText("");
		String firstname = FirstNameField.getText();
		String surname = SurnameField.getText();
		String username = UsernameFieldRegPNL.getText();
		String email = EmailField.getText();
		Date DOB = DOBPicker.getDate();
		char[] password = PasswordFieldRegPNL.getPassword();
		char[] repeatPassword = RepeatedPasswordField.getPassword();

		char[] tempPassword = PasswordFieldRegPNL.getPassword();
		String passwordStr = "";

		User user = new User(0, email, DOB, firstname, surname);
		UserCreds userCreds = new UserCreds(0, username, new String(password));

		for (int i = 0; i < tempPassword.length; i++) {
			passwordStr = passwordStr + tempPassword[i];
		}

		int passScore = calcPassScore(passwordStr);

		Validator validator = new Validator(firstname, surname, username, email, DOB, password, repeatPassword, passScore);
		String errorText = "";

		UserManager userManager = new UserManager();

		// Use Validator
		if (!validator.validateFirstname()) {
			errorText = "Please Enter your First Name.";
		} else if (!validator.validateFirstnameLength()) {
			errorText = "First Name is too long. Must be 100 or less characters.";
		} else if (!validator.validateSurname()) {
			errorText = "Please Enter your Surname.";
		} else if (!validator.validateSurnameLength()) {
			errorText = "Surname is too long. Must be 100 or less characters.";
		} else if (!validator.validateUsername()) {
			errorText = "Username does not follow correct format. Check the help for more information.";
		} else if (!validator.validateUsernameLength()) {
			errorText = "Username is too long. Must be 25 or less characters.";
		} else if (!validator.validateEmail()) {
			errorText = "Not a valid Email";
		} else if (!validator.validateEmailLength()) {
			errorText = "Email is too long. Must be 255 or less characters.";
		} else if (!validator.validateDOB()) {
			errorText = "Please Select your date of Birth.";
		} else if (!validator.validateDOBLogic()) {
			errorText = "Date of birth is in the future.";
		} else if (!validator.validatePasswordMatch()) {
			errorText = "Passwords do not match.";
		} else if (!validator.validatePasswordLength()) {
			errorText = "Password is too short. Must be greater than 8 characters.";
		} else if (!validator.validatePasswordStrength()) {
			errorText = "Your password is not strong enough. Try adding numbers or special charaters.";
		} else if (userManager.CheckForUser(username)) {
			errorText = "Username is already taken.";
		} else if (userManager.RegisterUser(user, userCreds)) {
			cardLayoutMain.show(MainPanel, "LoginPanel");
			JOptionPane.showMessageDialog(this,
							"Successfully Registered ✔"
							+ "\nPlease Login"
			);
		}

		ErrorTextRegPNL.setText(errorText);

        }//GEN-LAST:event_SignUpButtonRegPNLActionPerformed

        private void LoginInsteadButtonRegPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginInsteadButtonRegPNLActionPerformed
		cardLayoutMain.show(MainPanel, "LoginPanel"); // Switch to Login Panel
        }//GEN-LAST:event_LoginInsteadButtonRegPNLActionPerformed

  private void PasswordFieldRegPNLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldRegPNLMouseClicked
		// TODO add your handling code here:
  }//GEN-LAST:event_PasswordFieldRegPNLMouseClicked

  private void PasswordFieldRegPNLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldRegPNLKeyTyped
		char[] tempPassword = PasswordFieldRegPNL.getPassword();
		String password = "";

		for (int i = 0; i < tempPassword.length; i++) {
			password = password + tempPassword[i];
		}

		password = password + evt.getKeyChar();

		int score = calcPassScore(password);

		if (score == 0) {
			PasswordStrength.setValue(5);
		} else if (score < 3) {
			PasswordStrength.setValue(20);
		} else if (score < 4) {
			PasswordStrength.setValue(50);
		} else if (score < 6) {
			PasswordStrength.setValue(70);
		} else {
			PasswordStrength.setValue(100);
		}

  }//GEN-LAST:event_PasswordFieldRegPNLKeyTyped

  private void PasswordFieldRegPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldRegPNLActionPerformed
		// TODO add your handling code here:
  }//GEN-LAST:event_PasswordFieldRegPNLActionPerformed

  private void PasswordFieldRegPNLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldRegPNLKeyPressed

  }//GEN-LAST:event_PasswordFieldRegPNLKeyPressed

  private void PasswordFieldRegPNLInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_PasswordFieldRegPNLInputMethodTextChanged

  }//GEN-LAST:event_PasswordFieldRegPNLInputMethodTextChanged

  private void PasswordFieldRegPNLPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PasswordFieldRegPNLPropertyChange

  }//GEN-LAST:event_PasswordFieldRegPNLPropertyChange

  private void NewProjectButtonPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProjectButtonPVActionPerformed
		cardLayoutPV.show(CardPV, "NewProject");
  }//GEN-LAST:event_NewProjectButtonPVActionPerformed

  private void CreateProjectBTNNPPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateProjectBTNNPPVActionPerformed
		ProjectManager projectManager = new ProjectManager();

		if (ProjectNameTXTNPPV.getText().equals("")) {
			ErrorLabelNPPV.setText("Please Enter the Project Title");
		} else if (ProjectDescriptionLabelNPPV.getText().equals("")) {
			ErrorLabelNPPV.setText("Please Enter the Project Description");
		} else if (ProjectNameTXTNPPV.getText().length() > 100) {
			ErrorLabelNPPV.setText("Title is too long");
		} else if (ProjectDescriptionLabelNPPV.getText().length() > 300) {
			ErrorLabelNPPV.setText("Desription is too long");
		} else if (projectManager.CreateProject(ProjectNameTXTNPPV.getText(), DesriptionTextAreaNPPV.getText(), currentUser)) {
			cardLayoutPV.show(CardPV, "ProjectViewPV");
			JOptionPane.showMessageDialog(this,
							"Successfully Created Project ✔"
							+ "\nClick Refresh to see it"
			);
		}
  }//GEN-LAST:event_CreateProjectBTNNPPVActionPerformed

  private void RefreshButtonPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonPVActionPerformed
		CardPV.repaint();
		refreshProjectView();
		CardPV.repaint();
  }//GEN-LAST:event_RefreshButtonPVActionPerformed

  private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
		cardLayoutPV.show(CardPV, "NewProject");
		refreshProjectView();
		cardLayoutPV.show(CardPV, "ProjectViewPV");
  }//GEN-LAST:event_BackButtonActionPerformed

  private void AccountSetButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountSetButtonsActionPerformed
		cardLayoutPV.show(CardPV, "AccountSettings");
  }//GEN-LAST:event_AccountSetButtonsActionPerformed

  private void DeleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountButtonActionPerformed
		UserManager userManager = new UserManager();
		userManager.deleteAccount(currentUsername);
  }//GEN-LAST:event_DeleteAccountButtonActionPerformed

  private void ProjectViewCardPVComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ProjectViewCardPVComponentAdded

  }//GEN-LAST:event_ProjectViewCardPVComponentAdded

  private void ProjectViewCardPVComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProjectViewCardPVComponentShown

  }//GEN-LAST:event_ProjectViewCardPVComponentShown

  private void AccounSettingsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccounSettingsBackButtonActionPerformed
		refreshProjectView();
		cardLayoutPV.show(CardPV, "ProjectViewPV");
  }//GEN-LAST:event_AccounSettingsBackButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton AccounSettingsBackButton;
  private javax.swing.JLabel AccountIcon;
  private javax.swing.JLabel AccountName;
  private javax.swing.JPanel AccountPanel;
  private javax.swing.JButton AccountSetButtons;
  private javax.swing.JPanel AccountSettingToolbar;
  private javax.swing.JPanel AccountSettingsPanel;
  private javax.swing.JLabel AccountUsername;
  private javax.swing.JButton BackButton;
  public static javax.swing.JPanel CardPV;
  private javax.swing.JButton CreateProjectBTNNPPV;
  private org.jdesktop.swingx.JXDatePicker DOBPicker;
  private javax.swing.JButton DeleteAccountButton;
  private javax.swing.JTextArea DesriptionTextAreaNPPV;
  private javax.swing.JTextField EmailField;
  private javax.swing.JLabel ErrorLabelNPPV;
  private javax.swing.JLabel ErrorText;
  private javax.swing.JLabel ErrorTextRegPNL;
  private javax.swing.JTextField FirstNameField;
  private javax.swing.JPanel InitTitlePNL;
  private javax.swing.JPanel InitialPanel;
  private javax.swing.JPanel LogPNL;
  private javax.swing.JButton LoginInsteadButtonRegPNL;
  private javax.swing.JPanel LoginPanel;
  private javax.swing.JPanel MainPanel;
  private javax.swing.JSplitPane MainSplit;
  private javax.swing.JMenuBar MenuBar;
  private javax.swing.JButton NewProjectButtonPV;
  private javax.swing.JPanel NewProjectDetailsPV;
  private javax.swing.JPanel NewProjectViewPV;
  private javax.swing.JLabel PassStrengthText;
  private javax.swing.JPasswordField PasswordField;
  private javax.swing.JPasswordField PasswordFieldRegPNL;
  private javax.swing.JProgressBar PasswordStrength;
  private javax.swing.JLabel ProjectDescriptionLabelNPPV;
  private javax.swing.JLabel ProjectNameLabelNPPV;
  private javax.swing.JTextField ProjectNameTXTNPPV;
  private javax.swing.JPanel ProjectPage;
  private javax.swing.JScrollPane ProjectScrollViewPV;
  private javax.swing.JPanel ProjectView;
  private javax.swing.JPanel ProjectViewCardPV;
  private javax.swing.JPanel ProjectViewToolBarPV;
  private javax.swing.JButton RefreshButtonPV;
  private javax.swing.JPanel RegPNL;
  private javax.swing.JPanel RegisterPanel;
  private javax.swing.JPasswordField RepeatedPasswordField;
  private javax.swing.JPanel ScrollViewPV;
  private javax.swing.JSeparator SeperatorNPPV;
  private javax.swing.JPanel SidePane;
  private javax.swing.JButton SignInButtonLogPNL;
  private javax.swing.JButton SignInButtonPNL;
  private javax.swing.JButton SignUpButton;
  private javax.swing.JButton SignUpButtonRegPNL;
  private javax.swing.JButton SignUpInsteadButtonLogPNL;
  private javax.swing.JTextField SurnameField;
  private javax.swing.JScrollPane TextScrollNPPV;
  private javax.swing.JPanel ToolBarNPPV;
  private javax.swing.JTextField UsernameField;
  private javax.swing.JTextField UsernameFieldRegPNL;
  private javax.swing.JLabel UsernameText;
  private javax.swing.JLabel UsernameText1;
  private javax.swing.JLabel UsernameText2;
  private javax.swing.JLabel UsernameText3;
  private javax.swing.JLabel UsernameText4;
  private javax.swing.JLabel UsernameText5;
  private javax.swing.JLabel UsernameText6;
  private javax.swing.JLabel UsernameText7;
  private javax.swing.JLabel UsernameText8;
  private javax.swing.JLabel Welcome1Text;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JSeparator jSeparator1;
  // End of variables declaration//GEN-END:variables
}
