package GUI;

import DATA.Validator;
import java.util.Date;

public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SignUpText = new javax.swing.JLabel();
        UsernameText = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        UsernameText1 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        UsernameText2 = new javax.swing.JLabel();
        UsernameText3 = new javax.swing.JLabel();
        SurnameField = new javax.swing.JTextField();
        FirstNameField = new javax.swing.JTextField();
        UsernameText4 = new javax.swing.JLabel();
        UsernameText5 = new javax.swing.JLabel();
        DOBPicker = new org.jdesktop.swingx.JXDatePicker();
        PasswordField = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        ErrorText = new javax.swing.JLabel();
        LoginInsteadButton = new javax.swing.JButton();
        UsernameText6 = new javax.swing.JLabel();
        RepeatedPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setResizable(false);

        SignUpText.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        SignUpText.setText("Sign up");

        UsernameText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText.setText("Username");

        UsernameText1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText1.setText("Email");

        UsernameText2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText2.setText("Password");

        UsernameText3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText3.setText("Surname");

        UsernameText4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText4.setText("First Name");

        UsernameText5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText5.setText("Date Of Birth");

        SignUpButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        SignUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/icons8-add-user-male-24.png"))); // NOI18N
        SignUpButton.setText("Sign up");
        SignUpButton.setToolTipText("Click To Sign up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        ErrorText.setForeground(new java.awt.Color(255, 0, 51));

        LoginInsteadButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LoginInsteadButton.setText("Login Instead");
        LoginInsteadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginInsteadButtonActionPerformed(evt);
            }
        });

        UsernameText6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText6.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(SignUpText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameText6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LoginInsteadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EmailField)
                            .addComponent(UsernameText2)
                            .addComponent(UsernameText1)
                            .addComponent(UsernameField)
                            .addComponent(UsernameText)
                            .addComponent(SurnameField)
                            .addComponent(UsernameText3)
                            .addComponent(FirstNameField)
                            .addComponent(UsernameText4)
                            .addComponent(UsernameText5)
                            .addComponent(DOBPicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordField)
                            .addComponent(ErrorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RepeatedPasswordField))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOBPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepeatedPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginInsteadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SignUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        String firstname = FirstNameField.getText();
        String surname = SurnameField.getText();
        String username = UsernameField.getText();
        String email = EmailField.getText();
        Date DOB = DOBPicker.getDate();
        char[] password = PasswordField.getPassword();
        char[] repeatPassword = RepeatedPasswordField.getPassword();

        Validator validator = new Validator(firstname, surname, username, email, DOB, password, repeatPassword);

    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void LoginInsteadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginInsteadButtonActionPerformed
        LoginForm logForm = new LoginForm();
        logForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LoginInsteadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DOBPicker;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel ErrorText;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JButton LoginInsteadButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField RepeatedPasswordField;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel SignUpText;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameText;
    private javax.swing.JLabel UsernameText1;
    private javax.swing.JLabel UsernameText2;
    private javax.swing.JLabel UsernameText3;
    private javax.swing.JLabel UsernameText4;
    private javax.swing.JLabel UsernameText5;
    private javax.swing.JLabel UsernameText6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
